# Generated by Django 4.2.28 on 2026-02-04 11:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SleepLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(help_text="入睡时间")),
                ("end_time", models.DateTimeField(help_text="起床时间")),
                (
                    "duration_minutes",
                    models.IntegerField(editable=False, help_text="睡眠时长（分钟）"),
                ),
                (
                    "quality_rating",
                    models.IntegerField(
                        blank=True,
                        help_text="睡眠质量评分 (1-10)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="备注")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurement_sleeplogs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "睡眠记录",
                "verbose_name_plural": "睡眠记录",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="MedicationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="药物名称", max_length=200)),
                ("dosage", models.CharField(help_text="剂量", max_length=100)),
                ("frequency", models.CharField(help_text="服用频率", max_length=100)),
                ("start_date", models.DateField(help_text="开始日期")),
                ("end_date", models.DateField(blank=True, help_text="结束日期", null=True)),
                ("notes", models.TextField(blank=True, help_text="备注")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "药物记录",
                "verbose_name_plural": "药物记录",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Measurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("measured_at", models.DateTimeField()),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="体重 (kg)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "systolic",
                    models.IntegerField(blank=True, help_text="收缩压", null=True),
                ),
                (
                    "diastolic",
                    models.IntegerField(blank=True, help_text="舒张压", null=True),
                ),
                (
                    "blood_glucose",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="血糖 (mmol/L)",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "heart_rate",
                    models.IntegerField(blank=True, help_text="心率 (bpm)", null=True),
                ),
                ("notes", models.TextField(blank=True, help_text="备注")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "健康测量",
                "verbose_name_plural": "健康测量",
                "ordering": ["-measured_at"],
            },
        ),
        migrations.CreateModel(
            name="MoodLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="日期")),
                (
                    "rating",
                    models.IntegerField(
                        help_text="情绪评分 (1-10, 1为非常低落，10为非常愉悦)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="备注")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurement_moodlogs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "情绪记录",
                "verbose_name_plural": "情绪记录",
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
    ]
