# Generated by Django 6.0.2 on 2026-02-04 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_at', models.DateTimeField()),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, help_text='体重 (kg)', max_digits=5, null=True)),
                ('systolic', models.IntegerField(blank=True, help_text='收缩压', null=True)),
                ('diastolic', models.IntegerField(blank=True, help_text='舒张压', null=True)),
                ('blood_glucose', models.DecimalField(blank=True, decimal_places=1, help_text='血糖 (mmol/L)', max_digits=4, null=True)),
                ('heart_rate', models.IntegerField(blank=True, help_text='心率 (bpm)', null=True)),
                ('notes', models.TextField(blank=True, help_text='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '健康测量',
                'verbose_name_plural': '健康测量',
                'ordering': ['-measured_at'],
            },
        ),
    ]
