# Generated by Django 4.2.7 on 2026-02-10 02:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("measurements", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sleeplog",
            name="user",
        ),
        migrations.DeleteModel(
            name="MoodLog",
        ),
        migrations.DeleteModel(
            name="SleepLog",
        ),
    ]
