# Generated by Django 4.2.28 on 2026-02-04 10:58

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "管理员"), ("doctor", "医生"), ("user", "普通用户")],
                        default="user",
                        max_length=10,
                    ),
                ),
                ("is_doctor", models.BooleanField(default=False)),
                ("department", models.CharField(blank=True, max_length=100)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, help_text="用户头像", null=True, upload_to="avatars/"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "auth_user",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="SleepLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sleep_date", models.DateField(help_text="睡眠日期")),
                ("start_time", models.DateTimeField(help_text="入睡时间")),
                ("end_time", models.DateTimeField(help_text="起床时间")),
                ("duration_minutes", models.IntegerField(help_text="睡眠时长（分钟）")),
                (
                    "quality_rating",
                    models.IntegerField(
                        blank=True, help_text="睡眠质量评分 (1-10)", null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="备注")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_sleeplogs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "睡眠记录",
                "verbose_name_plural": "睡眠记录",
                "ordering": ["-sleep_date"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True, max_length=500)),
                ("location", models.CharField(blank=True, max_length=30)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("age", models.IntegerField(blank=True, help_text="年龄", null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "男"), ("F", "女"), ("O", "其他")],
                        help_text="性别",
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        choices=[
                            ("A", "A型"),
                            ("B", "B型"),
                            ("AB", "AB型"),
                            ("O", "O型"),
                            ("Unknown", "未知"),
                        ],
                        default="Unknown",
                        help_text="血型",
                        max_length=10,
                    ),
                ),
                (
                    "height_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="身高 (cm)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "weight_baseline_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="基准体重 (kg)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedicationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medication_name", models.CharField(help_text="药物名称", max_length=200)),
                ("dosage", models.CharField(help_text="剂量", max_length=100)),
                (
                    "frequency",
                    models.CharField(help_text="用药频率，例如: 每日3次", max_length=100),
                ),
                ("start_date", models.DateField(help_text="开始日期")),
                ("end_date", models.DateField(blank=True, help_text="结束日期", null=True)),
                ("notes", models.TextField(blank=True, help_text="备注")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medication_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "用药记录",
                "verbose_name_plural": "用药记录",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="MoodLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("log_date", models.DateField(help_text="记录日期")),
                (
                    "mood_rating",
                    models.IntegerField(help_text="心情评分 (1-10，1=很差，10=很好)"),
                ),
                ("notes", models.TextField(blank=True, help_text="心情备注")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_moodlogs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "心情记录",
                "verbose_name_plural": "心情记录",
                "ordering": ["-log_date"],
                "unique_together": {("user", "log_date")},
            },
        ),
    ]
